export const category = [
  { id: 1, name: "Cardiology" },
  { id: 2, name: "Dermatology" },
  { id: 3, name: "Endocrinology" },
  { id: 4, name: "Gastroenterology" },
  { id: 5, name: "Hematology" },
  { id: 6, name: "Infectious Disease" },
  { id: 7, name: "Nephrology" },
  { id: 8, name: "Neurology" },
  { id: 9, name: "Obstetrics and Gynecology" },
  { id: 10, name: "Oncology" },
  { id: 11, name: "Ophthalmology" },
  { id: 12, name: "Orthopedics" },
  { id: 13, name: "Otolaryngology (ENT)" },
  { id: 14, name: "Pediatrics" },
  { id: 15, name: "Psychiatry" },
  { id: 16, name: "Pulmonology" },
  { id: 17, name: "Rheumatology" },
  { id: 18, name: "Urology" },
  { id: 19, name: "Allergy and Immunology" },
  { id: 20, name: "Anesthesiology" },
  { id: 21, name: "Radiology" },
  { id: 22, name: "Pathology" },
  { id: 23, name: "Plastic Surgery" },
  { id: 24, name: "General Surgery" },
  { id: 25, name: "Family Medicine" },
  { id: 26, name: "Internal Medicine" },
  { id: 27, name: "Sports Medicine" },
  { id: 28, name: "Physical Medicine and Rehabilitation" },
  { id: 29, name: "Geriatrics" },
  { id: 30, name: "Palliative Care" },
];

export const cities = [
  { id: 1, name: "Karachi" },
  { id: 2, name: "Lahore" },
  { id: 3, name: "Islamabad" },
  { id: 4, name: "Rawalpindi" },
  { id: 5, name: "Faisalabad" },
  { id: 6, name: "Peshawar" },
  { id: 7, name: "Multan" },
  { id: 8, name: "Quetta" },
  { id: 9, name: "Sialkot" },
  { id: 10, name: "Gujranwala" },
  { id: 11, name: "Hyderabad" },
  { id: 12, name: "Sukkur" },
  { id: 13, name: "Bahawalpur" },
  { id: 14, name: "Sargodha" },
  { id: 15, name: "Mardan" },
  { id: 16, name: "Rahim Yar Khan" },
  { id: 17, name: "Abbottabad" },
  { id: 18, name: "Dera Ghazi Khan" },
  { id: 19, name: "Chiniot" },
  { id: 20, name: "Mingora" },
  { id: 21, name: "Nawabshah" },
  { id: 22, name: "Kasur" },
  { id: 23, name: "Jhelum" },
  { id: 24, name: "Okara" },
  { id: 25, name: "Mirpur Khas" },
  { id: 26, name: "Kotli" },
  { id: 27, name: "Chakwal" },
  { id: 28, name: "Khuzdar" },
  { id: 29, name: "Gwadar" },
  { id: 30, name: "Mansehra" },
  { id: 31, name: "Vehari" },
  { id: 32, name: "Sheikhupura" },
  { id: 33, name: "Turbat" },
  { id: 34, name: "Muzaffarabad" },
  { id: 35, name: "Hafizabad" },
  { id: 36, name: "Jhang" },
  { id: 37, name: "Khairpur" },
  { id: 38, name: "Tando Adam" },
  { id: 39, name: "Dadu" },
  { id: 40, name: "Ghotki" },
  { id: 41, name: "Larkana" },
  { id: 42, name: "Pakpattan" },
  { id: 43, name: "Badin" },
  { id: 44, name: "Sahiwal" },
  { id: 45, name: "Mianwali" },
  { id: 46, name: "Attock" },
  { id: 47, name: "Bhakkar" },
  { id: 48, name: "Jacobabad" },
  { id: 49, name: "Charsadda" },
  { id: 50, name: "Kohat" },
];

export const doctorsData = [
  {
    id: "D001",
    name: "Dr. Sarah Ahmed",
    degree: "MBBS, FCPS (Cardiology)",
    category: "Cardiology",
    hospital: "National Heart Institute",
    city: "Karachi",
    timing: "9:00 AM - 2:00 PM",
    experience: "15 years",
    fees: "Rs. 2000",
    contact: "+92 300 1234567",
    availableDays: ["Monday", "Wednesday", "Friday"],
    reviews: 4.7,
    specialization: "Heart Diseases, Hypertension, Angioplasty",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-123456",
  },
  {
    id: "D002",
    name: "Dr. Ahsan Khan",
    degree: "MBBS, MD (Dermatology)",
    category: "Dermatology",
    hospital: "Skin Health Clinic",
    city: "Lahore",
    timing: "10:00 AM - 4:00 PM",
    experience: "10 years",
    fees: "Rs. 1500",
    contact: "+92 300 2345678",
    availableDays: ["Tuesday", "Thursday", "Saturday"],
    reviews: 4.5,
    specialization: "Skin Care, Acne, Laser Treatments",
    gender: "Male",
    languagesSpoken: ["English", "Punjabi"],
    registrationNumber: "PMC-234567",
  },
  {
    id: "D003",
    name: "Dr. Maria Iqbal",
    degree: "MBBS, FCPS (Endocrinology)",
    category: "Endocrinology",
    hospital: "Metropolitan Medical Center",
    city: "Islamabad",
    timing: "8:00 AM - 1:00 PM",
    experience: "12 years",
    fees: "Rs. 1800",
    contact: "+92 300 3456789",
    availableDays: ["Monday", "Thursday", "Friday"],
    reviews: 4.6,
    specialization: "Diabetes, Thyroid Disorders, Hormonal Imbalance",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-345678",
  },
  {
    id: "D004",
    name: "Dr. Imran Raza",
    degree: "MBBS, MS (Gastroenterology)",
    category: "Gastroenterology",
    hospital: "City Medical Hospital",
    city: "Karachi",
    timing: "11:00 AM - 6:00 PM",
    experience: "20 years",
    fees: "Rs. 2500",
    contact: "+92 300 4567890",
    availableDays: ["Tuesday", "Friday", "Saturday"],
    reviews: 4.8,
    specialization: "Liver Disease, Endoscopy, Gastrointestinal Disorders",
    gender: "Male",
    languagesSpoken: ["English", "Sindhi"],
    registrationNumber: "PMC-456789",
  },
  {
    id: "D005",
    name: "Dr. Sana Malik",
    degree: "MBBS, MD (Pediatrics)",
    category: "Pediatrics",
    hospital: "Children's Medical Complex",
    city: "Peshawar",
    timing: "9:00 AM - 3:00 PM",
    experience: "8 years",
    fees: "Rs. 1200",
    contact: "+92 300 5678901",
    availableDays: ["Monday", "Wednesday", "Saturday"],
    reviews: 4.4,
    specialization: "Child Health, Immunization, Neonatology",
    gender: "Female",
    languagesSpoken: ["English", "Pashto"],
    registrationNumber: "PMC-567890",
  },
  {
    id: "D006",
    name: "Dr. Adeel Abbas",
    degree: "MBBS, FCPS (Neurology)",
    category: "Neurology",
    hospital: "Brain & Spine Center",
    city: "Rawalpindi",
    timing: "12:00 PM - 5:00 PM",
    experience: "11 years",
    fees: "Rs. 2200",
    contact: "+92 300 6789012",
    availableDays: ["Wednesday", "Friday", "Saturday"],
    reviews: 4.9,
    specialization: "Epilepsy, Stroke, Brain Injuries",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-678901",
  },
  {
    id: "D007",
    name: "Dr. Uzma Qureshi",
    degree: "MBBS, FCPS (Gynecology)",
    category: "Gynecology",
    hospital: "Women's Health Center",
    city: "Faisalabad",
    timing: "9:00 AM - 2:00 PM",
    experience: "14 years",
    fees: "Rs. 1800",
    contact: "+92 300 7890123",
    availableDays: ["Monday", "Tuesday", "Thursday"],
    reviews: 4.8,
    specialization: "Pregnancy Care, Fertility Treatments, Women's Health",
    gender: "Female",
    languagesSpoken: ["English", "Punjabi"],
    registrationNumber: "PMC-789012",
  },
  {
    id: "D008",
    name: "Dr. Bilal Aslam",
    degree: "MBBS, MD (Oncology)",
    category: "Oncology",
    hospital: "Cancer Care Hospital",
    city: "Multan",
    timing: "1:00 PM - 7:00 PM",
    experience: "9 years",
    fees: "Rs. 3000",
    contact: "+92 300 8901234",
    availableDays: ["Tuesday", "Thursday", "Friday"],
    reviews: 4.7,
    specialization: "Chemotherapy, Radiation, Tumor Surgery",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-890123",
  },
  {
    id: "D009",
    name: "Dr. Hira Zafar",
    degree: "MBBS, FCPS (Nephrology)",
    category: "Nephrology",
    hospital: "Kidney Care Clinic",
    city: "Quetta",
    timing: "10:00 AM - 4:00 PM",
    experience: "13 years",
    fees: "Rs. 2100",
    contact: "+92 300 9012345",
    availableDays: ["Wednesday", "Friday", "Sunday"],
    reviews: 4.5,
    specialization: "Kidney Transplants, Dialysis, Kidney Disease",
    gender: "Female",
    languagesSpoken: ["English", "Balochi"],
    registrationNumber: "PMC-901234",
  },
  {
    id: "D010",
    name: "Dr. Saad Farooq",
    degree: "MBBS, MS (Orthopedics)",
    category: "Orthopedics",
    hospital: "Bone & Joint Hospital",
    city: "Sialkot",
    timing: "8:00 AM - 2:00 PM",
    experience: "7 years",
    fees: "Rs. 1600",
    contact: "+92 300 0123456",
    availableDays: ["Monday", "Thursday", "Saturday"],
    reviews: 4.6,
    specialization: "Fractures, Joint Replacements, Arthritis",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-012345",
  },

  {
    id: "D011",
    name: "Dr. Aisha Tariq",
    degree: "MBBS, FCPS (Pediatrics)",
    category: "Pediatrics",
    hospital: "Kids Care Hospital",
    city: "Gujranwala",
    timing: "10:00 AM - 3:00 PM",
    experience: "5 years",
    fees: "Rs. 1000",
    contact: "+92 300 1234568",
    availableDays: ["Monday", "Wednesday", "Friday"],
    reviews: 4.4,
    specialization: "Child Health, Vaccination, Growth Disorders",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-123457",
  },
  {
    id: "D012",
    name: "Dr. Kashif Ali",
    degree: "MBBS, MD (Pulmonology)",
    category: "Pulmonology",
    hospital: "Lungs Health Clinic",
    city: "Hyderabad",
    timing: "9:00 AM - 4:00 PM",
    experience: "8 years",
    fees: "Rs. 1700",
    contact: "+92 300 2345679",
    availableDays: ["Tuesday", "Thursday"],
    reviews: 4.6,
    specialization: "Asthma, COPD, Lung Infections",
    gender: "Male",
    languagesSpoken: ["English", "Sindhi"],
    registrationNumber: "PMC-234568",
  },
  {
    id: "D013",
    name: "Dr. Fatima Noor",
    degree: "MBBS, MS (General Surgery)",
    category: "Surgery",
    hospital: "Surgical Care Center",
    city: "Faisalabad",
    timing: "1:00 PM - 6:00 PM",
    experience: "12 years",
    fees: "Rs. 2500",
    contact: "+92 300 3456790",
    availableDays: ["Monday", "Friday", "Sunday"],
    reviews: 4.8,
    specialization: "Abdominal Surgery, Laparoscopic Surgery, Trauma",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-345679",
  },
  {
    id: "D014",
    name: "Dr. Hassan Ahmed",
    degree: "MBBS, FCPS (Orthopedic)",
    category: "Orthopedics",
    hospital: "City Bone Hospital",
    city: "Lahore",
    timing: "9:00 AM - 3:00 PM",
    experience: "9 years",
    fees: "Rs. 1900",
    contact: "+92 300 4567891",
    availableDays: ["Tuesday", "Thursday", "Saturday"],
    reviews: 4.7,
    specialization: "Joint Pain, Sports Injuries, Surgery",
    gender: "Male",
    languagesSpoken: ["English", "Punjabi"],
    registrationNumber: "PMC-456790",
  },
  {
    id: "D015",
    name: "Dr. Nida Rahman",
    degree: "MBBS, MD (Psychiatry)",
    category: "Psychiatry",
    hospital: "Mental Health Clinic",
    city: "Karachi",
    timing: "10:00 AM - 5:00 PM",
    experience: "11 years",
    fees: "Rs. 2000",
    contact: "+92 300 5678902",
    availableDays: ["Wednesday", "Saturday"],
    reviews: 4.5,
    specialization: "Anxiety Disorders, Depression, Therapy",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-567891",
  },
  {
    id: "D016",
    name: "Dr. Amina Shaikh",
    degree: "MBBS, FCPS (Obstetrics & Gynecology)",
    category: "Gynecology",
    hospital: "Women's Care Hospital",
    city: "Peshawar",
    timing: "9:00 AM - 2:00 PM",
    experience: "10 years",
    fees: "Rs. 2100",
    contact: "+92 300 6789013",
    availableDays: ["Monday", "Thursday", "Saturday"],
    reviews: 4.6,
    specialization: "Pregnancy Care, Menstrual Disorders, Fertility",
    gender: "Female",
    languagesSpoken: ["English", "Pashto"],
    registrationNumber: "PMC-678902",
  },
  {
    id: "D017",
    name: "Dr. Zain Malik",
    degree: "MBBS, MD (Urology)",
    category: "Urology",
    hospital: "Urological Health Center",
    city: "Multan",
    timing: "10:00 AM - 5:00 PM",
    experience: "7 years",
    fees: "Rs. 1800",
    contact: "+92 300 7890124",
    availableDays: ["Tuesday", "Thursday", "Friday"],
    reviews: 4.4,
    specialization: "Kidney Stones, Prostate Issues, Surgery",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-789013",
  },
  {
    id: "D018",
    name: "Dr. Saima Bukhari",
    degree: "MBBS, FCPS (Rheumatology)",
    category: "Rheumatology",
    hospital: "Joint Health Hospital",
    city: "Islamabad",
    timing: "9:00 AM - 3:00 PM",
    experience: "6 years",
    fees: "Rs. 1700",
    contact: "+92 300 8901235",
    availableDays: ["Monday", "Wednesday", "Saturday"],
    reviews: 4.5,
    specialization: "Arthritis, Autoimmune Diseases, Pain Management",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-890234",
  },
  {
    id: "D019",
    name: "Dr. Raza Khan",
    degree: "MBBS, FCPS (ENT)",
    category: "ENT",
    hospital: "Ear Nose Throat Clinic",
    city: "Quetta",
    timing: "12:00 PM - 5:00 PM",
    experience: "13 years",
    fees: "Rs. 1600",
    contact: "+92 300 9012346",
    availableDays: ["Tuesday", "Friday", "Sunday"],
    reviews: 4.8,
    specialization: "Hearing Loss, Sinus Problems, Throat Disorders",
    gender: "Male",
    languagesSpoken: ["English", "Balochi"],
    registrationNumber: "PMC-901345",
  },
  {
    id: "D020",
    name: "Dr. Alina Qadir",
    degree: "MBBS, MD (Family Medicine)",
    category: "Family Medicine",
    hospital: "Family Health Clinic",
    city: "Gujrat",
    timing: "9:00 AM - 4:00 PM",
    experience: "4 years",
    fees: "Rs. 1400",
    contact: "+92 300 0123457",
    availableDays: ["Monday", "Wednesday", "Friday"],
    reviews: 4.3,
    specialization: "General Health, Preventive Care, Health Education",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-012456",
  },

  {
    id: "D021",
    name: "Dr. Bilal Khan",
    degree: "MBBS, FCPS (Cardiology)",
    category: "Cardiology",
    hospital: "Heart & Vascular Institute",
    city: "Karachi",
    timing: "9:00 AM - 3:00 PM",
    experience: "15 years",
    fees: "Rs. 2300",
    contact: "+92 300 1234569",
    availableDays: ["Monday", "Thursday", "Saturday"],
    reviews: 4.7,
    specialization: "Heart Disease, Angina, Heart Failure",
    gender: "Male",
    languagesSpoken: ["English", "Sindhi"],
    registrationNumber: "PMC-123458",
  },
  {
    id: "D022",
    name: "Dr. Naila Shah",
    degree: "MBBS, MD (Dermatology)",
    category: "Dermatology",
    hospital: "Glow Skin Clinic",
    city: "Lahore",
    timing: "10:00 AM - 4:00 PM",
    experience: "9 years",
    fees: "Rs. 1600",
    contact: "+92 300 2345680",
    availableDays: ["Tuesday", "Friday"],
    reviews: 4.6,
    specialization: "Acne Treatment, Psoriasis, Eczema",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-234569",
  },
  {
    id: "D023",
    name: "Dr. Shazia Malik",
    degree: "MBBS, FCPS (Endocrinology)",
    category: "Endocrinology",
    hospital: "Diabetes & Endocrine Clinic",
    city: "Islamabad",
    timing: "9:00 AM - 2:00 PM",
    experience: "12 years",
    fees: "Rs. 1900",
    contact: "+92 300 3456791",
    availableDays: ["Wednesday", "Saturday"],
    reviews: 4.8,
    specialization: "Diabetes Management, Thyroid Disorders",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-345680",
  },
  {
    id: "D024",
    name: "Dr. Qasim Raza",
    degree: "MBBS, MS (Gastroenterology)",
    category: "Gastroenterology",
    hospital: "Gastro Health Clinic",
    city: "Karachi",
    timing: "10:00 AM - 5:00 PM",
    experience: "10 years",
    fees: "Rs. 2200",
    contact: "+92 300 4567892",
    availableDays: ["Tuesday", "Thursday"],
    reviews: 4.7,
    specialization: "Digestive Disorders, Endoscopy",
    gender: "Male",
    languagesSpoken: ["English", "Punjabi"],
    registrationNumber: "PMC-456791",
  },
  {
    id: "D025",
    name: "Dr. Sadaf Awan",
    degree: "MBBS, MD (Pediatrics)",
    category: "Pediatrics",
    hospital: "Children's Hospital",
    city: "Peshawar",
    timing: "9:00 AM - 4:00 PM",
    experience: "8 years",
    fees: "Rs. 1300",
    contact: "+92 300 5678903",
    availableDays: ["Monday", "Friday", "Saturday"],
    reviews: 4.4,
    specialization: "Child Growth, Immunizations, Nutrition",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-567892",
  },
  {
    id: "D026",
    name: "Dr. Arif Malik",
    degree: "MBBS, FCPS (Neurology)",
    category: "Neurology",
    hospital: "Brain Care Center",
    city: "Rawalpindi",
    timing: "1:00 PM - 6:00 PM",
    experience: "14 years",
    fees: "Rs. 2400",
    contact: "+92 300 6789014",
    availableDays: ["Tuesday", "Thursday", "Saturday"],
    reviews: 4.9,
    specialization: "Headaches, Epilepsy, Neurodegenerative Disorders",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-678903",
  },
  {
    id: "D027",
    name: "Dr. Hira Khan",
    degree: "MBBS, MD (Gynecology)",
    category: "Gynecology",
    hospital: "Women's Health Clinic",
    city: "Faisalabad",
    timing: "9:00 AM - 3:00 PM",
    experience: "10 years",
    fees: "Rs. 2100",
    contact: "+92 300 7890125",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.6,
    specialization: "Pregnancy Care, Menopause, Fertility Treatments",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-789014",
  },
  {
    id: "D028",
    name: "Dr. Naveed Iqbal",
    degree: "MBBS, MD (Oncology)",
    category: "Oncology",
    hospital: "Cancer Center",
    city: "Multan",
    timing: "10:00 AM - 5:00 PM",
    experience: "9 years",
    fees: "Rs. 3000",
    contact: "+92 300 8901236",
    availableDays: ["Wednesday", "Friday", "Sunday"],
    reviews: 4.8,
    specialization: "Chemotherapy, Radiation Therapy, Palliative Care",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-890235",
  },
  {
    id: "D029",
    name: "Dr. Aiman Zafar",
    degree: "MBBS, FCPS (Nephrology)",
    category: "Nephrology",
    hospital: "Kidney Health Hospital",
    city: "Quetta",
    timing: "11:00 AM - 4:00 PM",
    experience: "12 years",
    fees: "Rs. 2000",
    contact: "+92 300 9012347",
    availableDays: ["Monday", "Thursday", "Saturday"],
    reviews: 4.7,
    specialization: "Dialysis, Kidney Stones, Hypertension",
    gender: "Female",
    languagesSpoken: ["English", "Balochi"],
    registrationNumber: "PMC-901346",
  },
  {
    id: "D030",
    name: "Dr. Faraz Ahmed",
    degree: "MBBS, MS (Orthopedics)",
    category: "Orthopedics",
    hospital: "Joint Care Center",
    city: "Sialkot",
    timing: "9:00 AM - 2:00 PM",
    experience: "5 years",
    fees: "Rs. 1700",
    contact: "+92 300 0123458",
    availableDays: ["Tuesday", "Friday"],
    reviews: 4.5,
    specialization: "Sports Injuries, Joint Replacement, Fractures",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-012457",
  },

  {
    id: "D031",
    name: "Dr. Sana Malik",
    degree: "MBBS, FCPS (Cardiology)",
    category: "Cardiology",
    hospital: "Heart Care Clinic",
    city: "Lahore",
    timing: "10:00 AM - 4:00 PM",
    experience: "10 years",
    fees: "Rs. 2500",
    contact: "+92 300 1234570",
    availableDays: ["Monday", "Wednesday", "Friday"],
    reviews: 4.6,
    specialization: "Heart Attack, High Blood Pressure, Cholesterol Management",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-123459",
  },
  {
    id: "D032",
    name: "Dr. Asad Hussain",
    degree: "MBBS, MD (Gastroenterology)",
    category: "Gastroenterology",
    hospital: "Digestive Health Center",
    city: "Karachi",
    timing: "9:00 AM - 5:00 PM",
    experience: "9 years",
    fees: "Rs. 2000",
    contact: "+92 300 2345791",
    availableDays: ["Tuesday", "Thursday"],
    reviews: 4.7,
    specialization: "IBD, GERD, Liver Diseases",
    gender: "Male",
    languagesSpoken: ["English", "Sindhi"],
    registrationNumber: "PMC-234570",
  },
  {
    id: "D033",
    name: "Dr. Noreen Khatun",
    degree: "MBBS, FCPS (Dermatology)",
    category: "Dermatology",
    hospital: "Clear Skin Clinic",
    city: "Islamabad",
    timing: "9:00 AM - 4:00 PM",
    experience: "8 years",
    fees: "Rs. 1800",
    contact: "+92 300 3457892",
    availableDays: ["Monday", "Friday", "Saturday"],
    reviews: 4.5,
    specialization: "Skin Diseases, Cosmetic Dermatology",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-345681",
  },
  {
    id: "D034",
    name: "Dr. Faizan Ali",
    degree: "MBBS, MD (Psychiatry)",
    category: "Psychiatry",
    hospital: "Mental Wellness Center",
    city: "Peshawar",
    timing: "10:00 AM - 5:00 PM",
    experience: "7 years",
    fees: "Rs. 2000",
    contact: "+92 300 4568903",
    availableDays: ["Tuesday", "Thursday"],
    reviews: 4.6,
    specialization: "Bipolar Disorder, Depression, Anxiety",
    gender: "Male",
    languagesSpoken: ["English", "Pashto"],
    registrationNumber: "PMC-456792",
  },
  {
    id: "D035",
    name: "Dr. Hira Shah",
    degree: "MBBS, FCPS (Pediatrics)",
    category: "Pediatrics",
    hospital: "Little Hearts Clinic",
    city: "Faisalabad",
    timing: "9:00 AM - 3:00 PM",
    experience: "5 years",
    fees: "Rs. 1200",
    contact: "+92 300 5679014",
    availableDays: ["Monday", "Wednesday", "Friday"],
    reviews: 4.4,
    specialization: "Neonatology, Child Health, Vaccinations",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-567893",
  },
  {
    id: "D036",
    name: "Dr. Saad Iqbal",
    degree: "MBBS, MD (Pulmonology)",
    category: "Pulmonology",
    hospital: "Breathing Easy Clinic",
    city: "Lahore",
    timing: "10:00 AM - 5:00 PM",
    experience: "6 years",
    fees: "Rs. 1900",
    contact: "+92 300 6789125",
    availableDays: ["Tuesday", "Friday"],
    reviews: 4.6,
    specialization: "Chronic Lung Disease, Allergies, Asthma",
    gender: "Male",
    languagesSpoken: ["English", "Punjabi"],
    registrationNumber: "PMC-678904",
  },
  {
    id: "D037",
    name: "Dr. Samina Bukhari",
    degree: "MBBS, MS (Gynecology)",
    category: "Gynecology",
    hospital: "Women’s Wellness Hospital",
    city: "Karachi",
    timing: "9:00 AM - 2:00 PM",
    experience: "11 years",
    fees: "Rs. 2200",
    contact: "+92 300 7890136",
    availableDays: ["Wednesday", "Saturday"],
    reviews: 4.8,
    specialization: "Pregnancy, Menstrual Issues, Hormonal Disorders",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-789015",
  },
  {
    id: "D038",
    name: "Dr. Kamran Rizvi",
    degree: "MBBS, FCPS (Neurosurgery)",
    category: "Neurosurgery",
    hospital: "Brain and Spine Center",
    city: "Quetta",
    timing: "10:00 AM - 5:00 PM",
    experience: "14 years",
    fees: "Rs. 3000",
    contact: "+92 300 8902347",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.9,
    specialization: "Spine Surgery, Brain Tumors, Epilepsy Surgery",
    gender: "Male",
    languagesSpoken: ["English", "Balochi"],
    registrationNumber: "PMC-890236",
  },
  {
    id: "D039",
    name: "Dr. Ayesha Khan",
    degree: "MBBS, MD (Family Medicine)",
    category: "Family Medicine",
    hospital: "Family Health Center",
    city: "Sialkot",
    timing: "9:00 AM - 3:00 PM",
    experience: "8 years",
    fees: "Rs. 1500",
    contact: "+92 300 9012348",
    availableDays: ["Tuesday", "Saturday"],
    reviews: 4.4,
    specialization: "General Health, Chronic Disease Management",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-901347",
  },
  {
    id: "D040",
    name: "Dr. Nabil Ahmed",
    degree: "MBBS, MD (Rheumatology)",
    category: "Rheumatology",
    hospital: "Joint Health Clinic",
    city: "Multan",
    timing: "10:00 AM - 4:00 PM",
    experience: "7 years",
    fees: "Rs. 1800",
    contact: "+92 300 0123468",
    availableDays: ["Wednesday", "Friday"],
    reviews: 4.5,
    specialization: "Arthritis, Fibromyalgia, Autoimmune Diseases",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-012458",
  },

  {
    id: "D041",
    name: "Dr. Shahid Hussain",
    degree: "MBBS, FCPS (Orthopedics)",
    category: "Orthopedics",
    hospital: "Orthopedic Health Center",
    city: "Karachi",
    timing: "9:00 AM - 2:00 PM",
    experience: "12 years",
    fees: "Rs. 2300",
    contact: "+92 300 1234581",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.7,
    specialization: "Joint Pain, Sports Injuries, Fractures",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-123460",
  },
  {
    id: "D042",
    name: "Dr. Hina Sheikh",
    degree: "MBBS, MD (Pediatrics)",
    category: "Pediatrics",
    hospital: "Pediatric Health Clinic",
    city: "Lahore",
    timing: "10:00 AM - 5:00 PM",
    experience: "6 years",
    fees: "Rs. 1500",
    contact: "+92 300 2345802",
    availableDays: ["Tuesday", "Saturday"],
    reviews: 4.5,
    specialization: "Child Development, Vaccination",
    gender: "Female",
    languagesSpoken: ["English", "Punjabi"],
    registrationNumber: "PMC-234581",
  },
  {
    id: "D043",
    name: "Dr. Bilal Shah",
    degree: "MBBS, FCPS (Ophthalmology)",
    category: "Ophthalmology",
    hospital: "Eye Care Hospital",
    city: "Islamabad",
    timing: "9:00 AM - 4:00 PM",
    experience: "9 years",
    fees: "Rs. 2000",
    contact: "+92 300 3456813",
    availableDays: ["Wednesday", "Friday"],
    reviews: 4.8,
    specialization: "Cataract Surgery, Lasik, Eye Diseases",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-345682",
  },
  {
    id: "D044",
    name: "Dr. Aisha Khan",
    degree: "MBBS, MD (Internal Medicine)",
    category: "Internal Medicine",
    hospital: "General Health Clinic",
    city: "Peshawar",
    timing: "10:00 AM - 3:00 PM",
    experience: "11 years",
    fees: "Rs. 2100",
    contact: "+92 300 4567824",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.6,
    specialization: "Chronic Diseases, Health Check-ups",
    gender: "Female",
    languagesSpoken: ["English", "Pashto"],
    registrationNumber: "PMC-456783",
  },
  {
    id: "D045",
    name: "Dr. Faheem Ali",
    degree: "MBBS, MD (Dermatology)",
    category: "Dermatology",
    hospital: "Radiant Skin Center",
    city: "Faisalabad",
    timing: "1:00 PM - 6:00 PM",
    experience: "10 years",
    fees: "Rs. 1800",
    contact: "+92 300 5678925",
    availableDays: ["Tuesday", "Friday"],
    reviews: 4.4,
    specialization: "Skin Conditions, Cosmetic Treatments",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-567894",
  },
  {
    id: "D046",
    name: "Dr. Rabia Aziz",
    degree: "MBBS, FCPS (Endocrinology)",
    category: "Endocrinology",
    hospital: "Hormone Health Clinic",
    city: "Karachi",
    timing: "9:00 AM - 2:00 PM",
    experience: "8 years",
    fees: "Rs. 1900",
    contact: "+92 300 6789036",
    availableDays: ["Wednesday", "Saturday"],
    reviews: 4.7,
    specialization: "Diabetes, Thyroid Disorders",
    gender: "Female",
    languagesSpoken: ["English", "Sindhi"],
    registrationNumber: "PMC-678905",
  },
  {
    id: "D047",
    name: "Dr. Nasir Mehmood",
    degree: "MBBS, MD (Psychiatry)",
    category: "Psychiatry",
    hospital: "Mental Health Center",
    city: "Multan",
    timing: "10:00 AM - 4:00 PM",
    experience: "6 years",
    fees: "Rs. 2000",
    contact: "+92 300 7890147",
    availableDays: ["Tuesday", "Friday"],
    reviews: 4.5,
    specialization: "Mental Disorders, Therapy",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-789016",
  },
  {
    id: "D048",
    name: "Dr. Zainab Javed",
    degree: "MBBS, MS (Gynecology)",
    category: "Gynecology",
    hospital: "Women's Health Center",
    city: "Sialkot",
    timing: "9:00 AM - 3:00 PM",
    experience: "7 years",
    fees: "Rs. 2100",
    contact: "+92 300 8901258",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.8,
    specialization: "Pregnancy Care, Menstrual Disorders",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-890237",
  },
  {
    id: "D049",
    name: "Dr. Samiullah Khan",
    degree: "MBBS, MD (Nephrology)",
    category: "Nephrology",
    hospital: "Kidney Health Clinic",
    city: "Quetta",
    timing: "10:00 AM - 5:00 PM",
    experience: "9 years",
    fees: "Rs. 2200",
    contact: "+92 300 9012456",
    availableDays: ["Wednesday", "Saturday"],
    reviews: 4.6,
    specialization: "Kidney Diseases, Dialysis",
    gender: "Male",
    languagesSpoken: ["English", "Balochi"],
    registrationNumber: "PMC-901348",
  },
  {
    id: "D050",
    name: "Dr. Fariha Asad",
    degree: "MBBS, MD (Oncology)",
    category: "Oncology",
    hospital: "Cancer Care Center",
    city: "Lahore",
    timing: "9:00 AM - 4:00 PM",
    experience: "8 years",
    fees: "Rs. 2500",
    contact: "+92 300 0124579",
    availableDays: ["Monday", "Friday"],
    reviews: 4.7,
    specialization: "Cancer Treatment, Chemotherapy",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-012459",
  },

  {
    id: "D051",
    name: "Dr. Bilal Zafar",
    degree: "MBBS, FCPS (ENT)",
    category: "ENT",
    hospital: "ENT Care Hospital",
    city: "Karachi",
    timing: "9:00 AM - 3:00 PM",
    experience: "5 years",
    fees: "Rs. 1500",
    contact: "+92 300 1234560",
    availableDays: ["Tuesday", "Thursday"],
    reviews: 4.5,
    specialization: "Hearing Disorders, Sinus Problems",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-123461",
  },
  {
    id: "D052",
    name: "Dr. Meher Bano",
    degree: "MBBS, MD (General Surgery)",
    category: "General Surgery",
    hospital: "Surgical Health Center",
    city: "Lahore",
    timing: "10:00 AM - 4:00 PM",
    experience: "7 years",
    fees: "Rs. 2200",
    contact: "+92 300 2345691",
    availableDays: ["Monday", "Friday"],
    reviews: 4.6,
    specialization: "Abdominal Surgery, Laparoscopy",
    gender: "Female",
    languagesSpoken: ["English", "Punjabi"],
    registrationNumber: "PMC-234582",
  },
  {
    id: "D053",
    name: "Dr. Omar Iftikhar",
    degree: "MBBS, MD (Urology)",
    category: "Urology",
    hospital: "Urological Health Center",
    city: "Islamabad",
    timing: "9:00 AM - 5:00 PM",
    experience: "8 years",
    fees: "Rs. 2000",
    contact: "+92 300 3456893",
    availableDays: ["Wednesday", "Saturday"],
    reviews: 4.7,
    specialization: "Kidney Stones, Prostate Issues",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-345683",
  },
  {
    id: "D054",
    name: "Dr. Huma Saeed",
    degree: "MBBS, FCPS (Cardiothoracic Surgery)",
    category: "Cardiothoracic Surgery",
    hospital: "Heart and Lung Hospital",
    city: "Peshawar",
    timing: "10:00 AM - 4:00 PM",
    experience: "9 years",
    fees: "Rs. 3000",
    contact: "+92 300 4567904",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.8,
    specialization: "Heart Surgery, Lung Surgery",
    gender: "Female",
    languagesSpoken: ["English", "Pashto"],
    registrationNumber: "PMC-456784",
  },
  {
    id: "D055",
    name: "Dr. Zain Sheikh",
    degree: "MBBS, MD (Anesthesiology)",
    category: "Anesthesiology",
    hospital: "Pain Relief Center",
    city: "Faisalabad",
    timing: "9:00 AM - 3:00 PM",
    experience: "6 years",
    fees: "Rs. 1700",
    contact: "+92 300 5678955",
    availableDays: ["Tuesday", "Friday"],
    reviews: 4.5,
    specialization: "Pain Management, Anesthesia",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-567895",
  },
  {
    id: "D056",
    name: "Dr. Sania Baloch",
    degree: "MBBS, MD (Radiology)",
    category: "Radiology",
    hospital: "Diagnostic Imaging Center",
    city: "Karachi",
    timing: "10:00 AM - 4:00 PM",
    experience: "5 years",
    fees: "Rs. 1800",
    contact: "+92 300 6789066",
    availableDays: ["Wednesday", "Saturday"],
    reviews: 4.4,
    specialization: "X-Ray, MRI, CT Scans",
    gender: "Female",
    languagesSpoken: ["English", "Sindhi"],
    registrationNumber: "PMC-678906",
  },
  {
    id: "D057",
    name: "Dr. Tariq Ahmed",
    degree: "MBBS, MD (Geriatrics)",
    category: "Geriatrics",
    hospital: "Senior Health Clinic",
    city: "Multan",
    timing: "9:00 AM - 2:00 PM",
    experience: "11 years",
    fees: "Rs. 1900",
    contact: "+92 300 7890148",
    availableDays: ["Tuesday", "Friday"],
    reviews: 4.6,
    specialization: "Aging Issues, Chronic Care",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-789017",
  },
  {
    id: "D058",
    name: "Dr. Nida Raza",
    degree: "MBBS, MD (Obstetrics)",
    category: "Obstetrics",
    hospital: "Maternity Health Center",
    city: "Sialkot",
    timing: "10:00 AM - 4:00 PM",
    experience: "7 years",
    fees: "Rs. 2100",
    contact: "+92 300 8901259",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.9,
    specialization: "Pregnancy Care, Delivery",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-890238",
  },
  {
    id: "D059",
    name: "Dr. Faisal Malik",
    degree: "MBBS, FCPS (Plastic Surgery)",
    category: "Plastic Surgery",
    hospital: "Aesthetic Surgery Center",
    city: "Quetta",
    timing: "10:00 AM - 5:00 PM",
    experience: "12 years",
    fees: "Rs. 2500",
    contact: "+92 300 9012457",
    availableDays: ["Wednesday", "Saturday"],
    reviews: 4.8,
    specialization: "Reconstructive Surgery, Cosmetic Surgery",
    gender: "Male",
    languagesSpoken: ["English", "Balochi"],
    registrationNumber: "PMC-901349",
  },
  {
    id: "D060",
    name: "Dr. Sara Qureshi",
    degree: "MBBS, MD (Nutrition)",
    category: "Nutrition",
    hospital: "Nutrition and Wellness Clinic",
    city: "Lahore",
    timing: "9:00 AM - 4:00 PM",
    experience: "5 years",
    fees: "Rs. 1400",
    contact: "+92 300 0124579",
    availableDays: ["Tuesday", "Friday"],
    reviews: 4.4,
    specialization: "Diet Planning, Weight Management",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-012460",
  },

  {
    id: "D061",
    name: "Dr. Aamir Khan",
    degree: "MBBS, MD (Family Medicine)",
    category: "Family Medicine",
    hospital: "Family Care Clinic",
    city: "Karachi",
    timing: "9:00 AM - 5:00 PM",
    experience: "10 years",
    fees: "Rs. 1800",
    contact: "+92 300 1234567",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.5,
    specialization: "Preventive Care, Chronic Disease Management",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-123462",
  },
  {
    id: "D062",
    name: "Dr. Ayesha Malik",
    degree: "MBBS, MD (Endocrinology)",
    category: "Endocrinology",
    hospital: "Diabetes Care Center",
    city: "Lahore",
    timing: "10:00 AM - 4:00 PM",
    experience: "8 years",
    fees: "Rs. 2100",
    contact: "+92 300 2345798",
    availableDays: ["Tuesday", "Saturday"],
    reviews: 4.6,
    specialization: "Diabetes Management, Hormonal Disorders",
    gender: "Female",
    languagesSpoken: ["English", "Punjabi"],
    registrationNumber: "PMC-234583",
  },
  {
    id: "D063",
    name: "Dr. Shahbaz Ahmed",
    degree: "MBBS, FCPS (Cardiology)",
    category: "Cardiology",
    hospital: "Heart Health Center",
    city: "Islamabad",
    timing: "9:00 AM - 4:00 PM",
    experience: "11 years",
    fees: "Rs. 2500",
    contact: "+92 300 3456909",
    availableDays: ["Wednesday", "Friday"],
    reviews: 4.7,
    specialization: "Heart Diseases, Hypertension",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-345684",
  },
  {
    id: "D064",
    name: "Dr. Nabila Khan",
    degree: "MBBS, MD (Gynecology)",
    category: "Gynecology",
    hospital: "Women's Health Hospital",
    city: "Peshawar",
    timing: "10:00 AM - 3:00 PM",
    experience: "7 years",
    fees: "Rs. 2200",
    contact: "+92 300 4567910",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.8,
    specialization: "Women’s Health, Fertility Issues",
    gender: "Female",
    languagesSpoken: ["English", "Pashto"],
    registrationNumber: "PMC-456785",
  },
  {
    id: "D065",
    name: "Dr. Saifullah Qureshi",
    degree: "MBBS, FCPS (Neurosurgery)",
    category: "Neurosurgery",
    hospital: "Neurosurgery Center",
    city: "Faisalabad",
    timing: "9:00 AM - 5:00 PM",
    experience: "10 years",
    fees: "Rs. 3000",
    contact: "+92 300 5678961",
    availableDays: ["Tuesday", "Saturday"],
    reviews: 4.9,
    specialization: "Brain Surgery, Spine Surgery",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-567896",
  },
  {
    id: "D066",
    name: "Dr. Lubna Farooq",
    degree: "MBBS, MD (Pediatrics)",
    category: "Pediatrics",
    hospital: "Child Health Clinic",
    city: "Karachi",
    timing: "10:00 AM - 4:00 PM",
    experience: "6 years",
    fees: "Rs. 1700",
    contact: "+92 300 6789072",
    availableDays: ["Wednesday", "Friday"],
    reviews: 4.5,
    specialization: "Child Health, Immunizations",
    gender: "Female",
    languagesSpoken: ["English", "Sindhi"],
    registrationNumber: "PMC-678908",
  },
  {
    id: "D067",
    name: "Dr. Haris Shah",
    degree: "MBBS, MD (Orthopedics)",
    category: "Orthopedics",
    hospital: "Bone Health Center",
    city: "Multan",
    timing: "9:00 AM - 3:00 PM",
    experience: "8 years",
    fees: "Rs. 1900",
    contact: "+92 300 7890174",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.6,
    specialization: "Joint Disorders, Sports Injuries",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-789018",
  },
  {
    id: "D068",
    name: "Dr. Zareen Javed",
    degree: "MBBS, MD (Dermatology)",
    category: "Dermatology",
    hospital: "Skin Care Center",
    city: "Sialkot",
    timing: "10:00 AM - 4:00 PM",
    experience: "9 years",
    fees: "Rs. 2000",
    contact: "+92 300 8901260",
    availableDays: ["Tuesday", "Friday"],
    reviews: 4.7,
    specialization: "Skin Conditions, Aesthetic Treatments",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-890239",
  },
  {
    id: "D069",
    name: "Dr. Umair Malik",
    degree: "MBBS, MD (Psychiatry)",
    category: "Psychiatry",
    hospital: "Mental Wellness Center",
    city: "Quetta",
    timing: "9:00 AM - 3:00 PM",
    experience: "7 years",
    fees: "Rs. 1800",
    contact: "+92 300 9012567",
    availableDays: ["Monday", "Saturday"],
    reviews: 4.4,
    specialization: "Mental Health, Therapy",
    gender: "Male",
    languagesSpoken: ["English", "Balochi"],
    registrationNumber: "PMC-901350",
  },
  {
    id: "D070",
    name: "Dr. Shirin Iqbal",
    degree: "MBBS, MD (Gastroenterology)",
    category: "Gastroenterology",
    hospital: "Digestive Health Center",
    city: "Lahore",
    timing: "10:00 AM - 4:00 PM",
    experience: "8 years",
    fees: "Rs. 2100",
    contact: "+92 300 0124580",
    availableDays: ["Tuesday", "Friday"],
    reviews: 4.5,
    specialization: "Digestive Disorders, Endoscopy",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-012461",
  },

  {
    id: "D071",
    name: "Dr. Noman Farid",
    degree: "MBBS, MD (Ophthalmology)",
    category: "Ophthalmology",
    hospital: "Eye Care Hospital",
    city: "Karachi",
    timing: "9:00 AM - 5:00 PM",
    experience: "6 years",
    fees: "Rs. 1600",
    contact: "+92 300 1234578",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.6,
    specialization: "Cataract Surgery, LASIK",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-123463",
  },
  {
    id: "D072",
    name: "Dr. Nida Rehman",
    degree: "MBBS, MD (Pediatrics)",
    category: "Pediatrics",
    hospital: "Kids Care Clinic",
    city: "Lahore",
    timing: "10:00 AM - 4:00 PM",
    experience: "5 years",
    fees: "Rs. 1500",
    contact: "+92 300 2345789",
    availableDays: ["Wednesday", "Saturday"],
    reviews: 4.8,
    specialization: "Child Development, Vaccinations",
    gender: "Female",
    languagesSpoken: ["English", "Punjabi"],
    registrationNumber: "PMC-234584",
  },
  {
    id: "D073",
    name: "Dr. Yasir Qureshi",
    degree: "MBBS, MD (Orthopedics)",
    category: "Orthopedics",
    hospital: "Orthopedic Hospital",
    city: "Islamabad",
    timing: "9:00 AM - 4:00 PM",
    experience: "10 years",
    fees: "Rs. 2300",
    contact: "+92 300 3456910",
    availableDays: ["Tuesday", "Friday"],
    reviews: 4.5,
    specialization: "Fractures, Joint Replacement",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-345685",
  },
  {
    id: "D074",
    name: "Dr. Fariha Ahmed",
    degree: "MBBS, MD (Dermatology)",
    category: "Dermatology",
    hospital: "Beauty Skin Clinic",
    city: "Peshawar",
    timing: "10:00 AM - 3:00 PM",
    experience: "8 years",
    fees: "Rs. 2000",
    contact: "+92 300 4567921",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.7,
    specialization: "Skin Diseases, Cosmetic Procedures",
    gender: "Female",
    languagesSpoken: ["English", "Pashto"],
    registrationNumber: "PMC-456786",
  },
  {
    id: "D075",
    name: "Dr. Asad Malik",
    degree: "MBBS, MD (Gastroenterology)",
    category: "Gastroenterology",
    hospital: "Gastro Health Center",
    city: "Faisalabad",
    timing: "9:00 AM - 5:00 PM",
    experience: "9 years",
    fees: "Rs. 2200",
    contact: "+92 300 5678972",
    availableDays: ["Tuesday", "Saturday"],
    reviews: 4.8,
    specialization: "Liver Diseases, Endoscopy",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-567897",
  },
  {
    id: "D076",
    name: "Dr. Rabia Khan",
    degree: "MBBS, MD (Psychiatry)",
    category: "Psychiatry",
    hospital: "Mental Health Institute",
    city: "Karachi",
    timing: "10:00 AM - 4:00 PM",
    experience: "7 years",
    fees: "Rs. 1800",
    contact: "+92 300 6789083",
    availableDays: ["Wednesday", "Friday"],
    reviews: 4.6,
    specialization: "Mental Health Disorders, Therapy",
    gender: "Female",
    languagesSpoken: ["English", "Sindhi"],
    registrationNumber: "PMC-678909",
  },
  {
    id: "D077",
    name: "Dr. Saad Javed",
    degree: "MBBS, MD (Neurology)",
    category: "Neurology",
    hospital: "Neuro Care Center",
    city: "Multan",
    timing: "9:00 AM - 3:00 PM",
    experience: "11 years",
    fees: "Rs. 2500",
    contact: "+92 300 7890182",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.5,
    specialization: "Headaches, Neurological Disorders",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-789019",
  },
  {
    id: "D078",
    name: "Dr. Hania Farooq",
    degree: "MBBS, MD (Pediatrics)",
    category: "Pediatrics",
    hospital: "Child Health Center",
    city: "Sialkot",
    timing: "10:00 AM - 4:00 PM",
    experience: "6 years",
    fees: "Rs. 1600",
    contact: "+92 300 8901274",
    availableDays: ["Tuesday", "Friday"],
    reviews: 4.7,
    specialization: "Child Health, Immunizations",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-890240",
  },
  {
    id: "D079",
    name: "Dr. Arslan Qadir",
    degree: "MBBS, MD (Pulmonology)",
    category: "Pulmonology",
    hospital: "Lung Health Center",
    city: "Quetta",
    timing: "9:00 AM - 5:00 PM",
    experience: "9 years",
    fees: "Rs. 2200",
    contact: "+92 300 9012579",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.5,
    specialization: "Respiratory Issues, Asthma",
    gender: "Male",
    languagesSpoken: ["English", "Balochi"],
    registrationNumber: "PMC-901351",
  },
  {
    id: "D080",
    name: "Dr. Naima Jahan",
    degree: "MBBS, MD (Nutrition)",
    category: "Nutrition",
    hospital: "Diet and Nutrition Clinic",
    city: "Lahore",
    timing: "10:00 AM - 4:00 PM",
    experience: "5 years",
    fees: "Rs. 1500",
    contact: "+92 300 0124591",
    availableDays: ["Tuesday", "Saturday"],
    reviews: 4.6,
    specialization: "Diet Planning, Weight Loss",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-012462",
  },

  {
    id: "D081",
    name: "Dr. Farhan Ahmed",
    degree: "MBBS, MD (Cardiology)",
    category: "Cardiology",
    hospital: "Heart Care Hospital",
    city: "Karachi",
    timing: "9:00 AM - 5:00 PM",
    experience: "12 years",
    fees: "Rs. 2800",
    contact: "+92 300 1234589",
    availableDays: ["Monday", "Wednesday"],
    reviews: 4.9,
    specialization: "Coronary Artery Disease, Heart Failure",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-123464",
  },
  {
    id: "D082",
    name: "Dr. Zainab Malik",
    degree: "MBBS, MD (Endocrinology)",
    category: "Endocrinology",
    hospital: "Diabetes Wellness Center",
    city: "Lahore",
    timing: "10:00 AM - 4:00 PM",
    experience: "9 years",
    fees: "Rs. 2400",
    contact: "+92 300 2345790",
    availableDays: ["Tuesday", "Thursday"],
    reviews: 4.8,
    specialization: "Thyroid Disorders, Diabetes",
    gender: "Female",
    languagesSpoken: ["English", "Punjabi"],
    registrationNumber: "PMC-234585",
  },
  {
    id: "D083",
    name: "Dr. Bilal Ahmed",
    degree: "MBBS, MD (General Surgery)",
    category: "General Surgery",
    hospital: "Surgical Hospital",
    city: "Islamabad",
    timing: "9:00 AM - 5:00 PM",
    experience: "10 years",
    fees: "Rs. 2500",
    contact: "+92 300 3456921",
    availableDays: ["Wednesday", "Friday"],
    reviews: 4.7,
    specialization: "Laparoscopic Surgery, Abdominal Surgery",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-345686",
  },
  {
    id: "D084",
    name: "Dr. Fizza Khan",
    degree: "MBBS, MD (Gynecology)",
    category: "Gynecology",
    hospital: "Women's Health Center",
    city: "Peshawar",
    timing: "10:00 AM - 3:00 PM",
    experience: "6 years",
    fees: "Rs. 2300",
    contact: "+92 300 4567935",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.6,
    specialization: "Pregnancy Care, Menstrual Disorders",
    gender: "Female",
    languagesSpoken: ["English", "Pashto"],
    registrationNumber: "PMC-456787",
  },
  {
    id: "D085",
    name: "Dr. Salman Tariq",
    degree: "MBBS, MD (Urology)",
    category: "Urology",
    hospital: "Urology Hospital",
    city: "Faisalabad",
    timing: "9:00 AM - 5:00 PM",
    experience: "8 years",
    fees: "Rs. 2100",
    contact: "+92 300 5678986",
    availableDays: ["Tuesday", "Saturday"],
    reviews: 4.5,
    specialization: "Kidney Disorders, Prostate Issues",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-567898",
  },
  {
    id: "D086",
    name: "Dr. Ayesha Noor",
    degree: "MBBS, MD (Internal Medicine)",
    category: "Internal Medicine",
    hospital: "Health Plus Clinic",
    city: "Karachi",
    timing: "10:00 AM - 4:00 PM",
    experience: "7 years",
    fees: "Rs. 1900",
    contact: "+92 300 6789098",
    availableDays: ["Wednesday", "Friday"],
    reviews: 4.4,
    specialization: "Chronic Diseases, Preventive Medicine",
    gender: "Female",
    languagesSpoken: ["English", "Sindhi"],
    registrationNumber: "PMC-678910",
  },
  {
    id: "D087",
    name: "Dr. Asif Jamil",
    degree: "MBBS, MD (Otolaryngology)",
    category: "ENT",
    hospital: "ENT Health Center",
    city: "Multan",
    timing: "9:00 AM - 3:00 PM",
    experience: "9 years",
    fees: "Rs. 1800",
    contact: "+92 300 7890197",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.5,
    specialization: "Ear, Nose, Throat Disorders",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-789020",
  },
  {
    id: "D088",
    name: "Dr. Samira Javed",
    degree: "MBBS, MD (Psychiatry)",
    category: "Psychiatry",
    hospital: "Mind Care Center",
    city: "Sialkot",
    timing: "10:00 AM - 4:00 PM",
    experience: "5 years",
    fees: "Rs. 1600",
    contact: "+92 300 8901280",
    availableDays: ["Tuesday", "Friday"],
    reviews: 4.8,
    specialization: "Anxiety Disorders, Depression",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-890241",
  },
  {
    id: "D089",
    name: "Dr. Naveed Iqbal",
    degree: "MBBS, MD (Pulmonology)",
    category: "Pulmonology",
    hospital: "Pulmonary Care Clinic",
    city: "Quetta",
    timing: "9:00 AM - 5:00 PM",
    experience: "10 years",
    fees: "Rs. 2300",
    contact: "+92 300 9012586",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.6,
    specialization: "Asthma, COPD",
    gender: "Male",
    languagesSpoken: ["English", "Balochi"],
    registrationNumber: "PMC-901352",
  },
  {
    id: "D090",
    name: "Dr. Rabia Anwar",
    degree: "MBBS, MD (Nutrition)",
    category: "Nutrition",
    hospital: "Healthy Living Clinic",
    city: "Lahore",
    timing: "10:00 AM - 4:00 PM",
    experience: "6 years",
    fees: "Rs. 1700",
    contact: "+92 300 0124607",
    availableDays: ["Tuesday", "Saturday"],
    reviews: 4.7,
    specialization: "Weight Management, Diet Counseling",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-012463",
  },

  {
    id: "D091",
    name: "Dr. Hamza Ali",
    degree: "MBBS, MD (Orthopedics)",
    category: "Orthopedics",
    hospital: "Bone and Joint Clinic",
    city: "Karachi",
    timing: "9:00 AM - 5:00 PM",
    experience: "12 years",
    fees: "Rs. 2600",
    contact: "+92 300 1122345",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.7,
    specialization: "Arthritis, Sports Injuries",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-1234567",
  },
  {
    id: "D092",
    name: "Dr. Hira Faisal",
    degree: "MBBS, MD (Gynecology)",
    category: "Gynecology",
    hospital: "Women Wellness Center",
    city: "Lahore",
    timing: "10:00 AM - 3:00 PM",
    experience: "9 years",
    fees: "Rs. 2100",
    contact: "+92 300 2233456",
    availableDays: ["Tuesday", "Friday"],
    reviews: 4.6,
    specialization: "Pregnancy Care, Hormonal Issues",
    gender: "Female",
    languagesSpoken: ["English", "Punjabi"],
    registrationNumber: "PMC-2345678",
  },
  {
    id: "D093",
    name: "Dr. Zafar Iqbal",
    degree: "MBBS, MD (Cardiology)",
    category: "Cardiology",
    hospital: "Heart Specialist Hospital",
    city: "Islamabad",
    timing: "9:00 AM - 5:00 PM",
    experience: "15 years",
    fees: "Rs. 3000",
    contact: "+92 300 3344567",
    availableDays: ["Wednesday", "Saturday"],
    reviews: 4.9,
    specialization: "Heart Failure, High Blood Pressure",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-3456789",
  },
  {
    id: "D094",
    name: "Dr. Rida Khurram",
    degree: "MBBS, MD (Psychiatry)",
    category: "Psychiatry",
    hospital: "Mental Wellness Clinic",
    city: "Peshawar",
    timing: "10:00 AM - 4:00 PM",
    experience: "7 years",
    fees: "Rs. 1800",
    contact: "+92 300 4455678",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.8,
    specialization: "Mental Health, Anxiety Disorders",
    gender: "Female",
    languagesSpoken: ["English", "Pashto"],
    registrationNumber: "PMC-4567890",
  },
  {
    id: "D095",
    name: "Dr. Saif Ullah",
    degree: "MBBS, MD (Pulmonology)",
    category: "Pulmonology",
    hospital: "Lung Health Center",
    city: "Quetta",
    timing: "9:00 AM - 5:00 PM",
    experience: "10 years",
    fees: "Rs. 2200",
    contact: "+92 300 5566789",
    availableDays: ["Tuesday", "Friday"],
    reviews: 4.5,
    specialization: "Asthma, Respiratory Infections",
    gender: "Male",
    languagesSpoken: ["English", "Balochi"],
    registrationNumber: "PMC-5678901",
  },
  {
    id: "D096",
    name: "Dr. Yasmin Jameel",
    degree: "MBBS, MD (Pediatrics)",
    category: "Pediatrics",
    hospital: "Child Health Clinic",
    city: "Sialkot",
    timing: "10:00 AM - 3:00 PM",
    experience: "5 years",
    fees: "Rs. 1500",
    contact: "+92 300 6677890",
    availableDays: ["Wednesday", "Saturday"],
    reviews: 4.6,
    specialization: "Vaccinations, Child Health",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-6789012",
  },
  {
    id: "D097",
    name: "Dr. Ali Qamar",
    degree: "MBBS, MD (Dermatology)",
    category: "Dermatology",
    hospital: "Skin Care Clinic",
    city: "Multan",
    timing: "9:00 AM - 4:00 PM",
    experience: "6 years",
    fees: "Rs. 1800",
    contact: "+92 300 7788901",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.4,
    specialization: "Skin Allergies, Acne Treatment",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-7890123",
  },
  {
    id: "D098",
    name: "Dr. Sana Imran",
    degree: "MBBS, MD (Endocrinology)",
    category: "Endocrinology",
    hospital: "Diabetes Care Center",
    city: "Faisalabad",
    timing: "10:00 AM - 3:00 PM",
    experience: "8 years",
    fees: "Rs. 2000",
    contact: "+92 300 8899012",
    availableDays: ["Tuesday", "Saturday"],
    reviews: 4.7,
    specialization: "Diabetes, Thyroid Disorders",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-8901234",
  },
  {
    id: "D099",
    name: "Dr. Mohsin Tariq",
    degree: "MBBS, MD (Gastroenterology)",
    category: "Gastroenterology",
    hospital: "Digestive Health Clinic",
    city: "Rawalpindi",
    timing: "9:00 AM - 5:00 PM",
    experience: "9 years",
    fees: "Rs. 2500",
    contact: "+92 300 9912345",
    availableDays: ["Wednesday", "Friday"],
    reviews: 4.8,
    specialization: "Liver Issues, Endoscopy",
    gender: "Male",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-9012345",
  },
  {
    id: "D100",
    name: "Dr. Sara Kamal",
    degree: "MBBS, MD (Nutrition)",
    category: "Nutrition",
    hospital: "Healthy Diet Clinic",
    city: "Lahore",
    timing: "10:00 AM - 4:00 PM",
    experience: "6 years",
    fees: "Rs. 1700",
    contact: "+92 300 9923456",
    availableDays: ["Monday", "Thursday"],
    reviews: 4.7,
    specialization: "Diet Planning, Weight Loss",
    gender: "Female",
    languagesSpoken: ["English", "Urdu"],
    registrationNumber: "PMC-0123456",
  },
];
